const TOKEN = {
    SET_TOKEN: 'SET_TOKEN',
    SET_LOGIN: 'SET_LOGIN',
    SET_LOGOUT: 'SET_LOGOUT',
    SET_PROFILE: 'SET_PROFILE',
    SET_ROOMID: 'SET_ROOMID',
    SET_PLAYERID: 'SET_PLAYERID',
    SET_NICKNAME: 'SET_NICKNAME',
    SET_OPENVIDUTOKEN: 'SET_OPENVIDUTOKEN',
}

const INGAME = {
    SET_PHASE: 'SET_PHASE',
    SET_DATE: 'SET_DATE',
}

export {
    TOKEN,
    INGAME
} 