const TOKEN = {
    SET_TOKEN: 'SET_TOKEN',
    SET_LOGIN: 'SET_LOGIN',
    SET_LOGOUT: 'SET_LOGOUT',
    SET_PROFILE: 'SET_PROFILE',
    SET_ROOMID: 'SET_ROOMID',
    SET_PLAYERID: 'SET_PLAYERID',
}

const INGAME = {
    
}

export {
    TOKEN,
    INGAME
} 